version: "3.7"

services:
  postgres_diero:
    image: postgres:latest
    hostname: postgres
    container_name: postgres_instance_diero
    environment:
      POSTGRES_DB: diero
      POSTGRES_USER: diero
      POSTGRES_PASSWORD: diero
    ports:
      - "5432:5432"
